apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-sample-app
spec:
  project: default
  source:
    repoURL: https://github.com/Suraj5260/ArgoCD-test.git
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
